"""Desktop runtime interfaces and fake implementations."""

from src.desktop.client import DESKTOP_NOT_IMPLEMENTED, DesktopClient, desktop_capabilities
from src.desktop.factory import build_default_desktop_client
from src.desktop.fake_client import FakeDesktopClient
from src.desktop.models import (
    DesktopAxFindRequest,
    DesktopAxFindResult,
    BridgePingResult,
    CapabilityDescriptor,
    CapabilityListResult,
    DesktopAxSnapshotRequest,
    DesktopAxSnapshotResult,
    DesktopClickRequest,
    DesktopClearStopRequest,
    DesktopControlResult,
    DesktopDragRequest,
    DesktopEmergencyStopRequest,
    DesktopElementSelector,
    DesktopFocusWindowRequest,
    DesktopFrontmostAppRequest,
    DesktopFrontmostAppResult,
    DesktopHotkeyRequest,
    DesktopLaunchAppRequest,
    DesktopRequestBase,
    DesktopRuntimeStatusRequest,
    DesktopRuntimeStatusResult,
    DesktopScrollRequest,
    DesktopScreenshotRequest,
    DesktopScreenshotResult,
    DesktopTargetDescriptor,
    DesktopTypeRequest,
    DesktopWaitElementRequest,
    DesktopWaitElementResult,
    DesktopWaitWindowRequest,
    DesktopWaitWindowResult,
    DesktopWindowBounds,
    DesktopWindowDescriptor,
    DesktopWindowsRequest,
    DesktopWindowsResult,
)
from src.desktop.pyobjc_client import PyObjCDesktopClient
from src.desktop.runtime import (
    DesktopRuntimeSnapshot,
    DesktopRuntimeState,
    DesktopRuntimeStoppedError,
    get_default_desktop_runtime_state,
)

__all__ = [
    "DESKTOP_NOT_IMPLEMENTED",
    "DesktopClient",
    "FakeDesktopClient",
    "PyObjCDesktopClient",
    "build_default_desktop_client",
    "desktop_capabilities",
    "BridgePingResult",
    "CapabilityDescriptor",
    "CapabilityListResult",
    "DesktopAxFindRequest",
    "DesktopAxFindResult",
    "DesktopAxSnapshotRequest",
    "DesktopAxSnapshotResult",
    "DesktopClickRequest",
    "DesktopClearStopRequest",
    "DesktopControlResult",
    "DesktopDragRequest",
    "DesktopEmergencyStopRequest",
    "DesktopElementSelector",
    "DesktopFocusWindowRequest",
    "DesktopFrontmostAppRequest",
    "DesktopFrontmostAppResult",
    "DesktopHotkeyRequest",
    "DesktopLaunchAppRequest",
    "DesktopRequestBase",
    "DesktopRuntimeSnapshot",
    "DesktopRuntimeState",
    "DesktopRuntimeStatusRequest",
    "DesktopRuntimeStatusResult",
    "DesktopRuntimeStoppedError",
    "DesktopScrollRequest",
    "DesktopScreenshotRequest",
    "DesktopScreenshotResult",
    "DesktopTargetDescriptor",
    "DesktopTypeRequest",
    "DesktopWaitElementRequest",
    "DesktopWaitElementResult",
    "DesktopWaitWindowRequest",
    "DesktopWaitWindowResult",
    "DesktopWindowBounds",
    "DesktopWindowDescriptor",
    "DesktopWindowsRequest",
    "DesktopWindowsResult",
    "get_default_desktop_runtime_state",
]
