from pathlib import Path
import json,re,html
from markdown_it import MarkdownIt
R=Path(__file__).resolve().parent
md=(R/'report-en.md').read_text()
body=MarkdownIt('commonmark',{'html':True}).enable('table').render(md)
for name in ['MOVING','AGENT']:
 lower=name.lower()
 body=body.replace('<!-- VIDEO_'+name+' -->',f'<figure><video controls playsinline preload="metadata" poster="media/{lower}-poster.jpg" aria-label="Video {lower}"><source src="media/{lower}.mp4" type="video/mp4"></video><figcaption>Recorded MuJoCo render · Approx. 3× playback · No audio · Simulation only</figcaption></figure>')
replay='''<section class="replay" aria-label="Recorded observation replay"><div class="controls"><label>Scenario <select id="case"><option value="0">A: Moving obstacle</option><option value="1">B: Temporary closure and Agent</option></select></label><button id="play" type="button">Play</button><output id="clock"></output></div><label class="slider-label" for="time">Simulation time [s]</label><input id="time" type="range" min="0" max="87.39" step="0.001" value="0"><svg id="scene" viewBox="0 0 840 640" role="img" aria-label="Recorded Go2 planar position and obstacles"></svg><div class="legend"><span>● Green: Go2 / trail</span><span>■ Gray: room geometry</span><span>● Orange: observed obstacle</span></div><p id="state"></p><p id="event"></p><p class="fine">Latest observation at or before the selected time. No interpolation or prediction. Closures follow recorded events. Playback is independent of the videos.</p></section>'''
body=body.replace('<!-- REPLAY -->',replay)
heads=[]
def heading(m):
 idx=len(heads)+1;heads.append((idx,m.group(1)));return f'<h2 id="s{idx}">{m.group(1)}</h2>'
body=re.sub(r'<h2>(.*?)</h2>',heading,body)
body=body.replace('<h1>MissionOS × Go2: From Agent Supervision to Verified Delivery</h1>','<h1>MissionOS × Go2<br>From Agent Supervision to Verified Delivery</h1>')
nav=''.join(f'<a href="#s{i}">{t}</a>' for i,t in heads)
dataset=(R/'data/replay.json').read_text().replace('<','\\u003c')
css='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f4f6f5;color:#1b3037;font:16px/1.9 -apple-system,BlinkMacSystemFont,"Hiragino Kaku Gothic ProN","Yu Gothic",sans-serif}a{color:#086657;text-underline-offset:3px}header{background:#123b39;color:#fff;padding:20px max(22px,calc((100vw - 1100px)/2));font-size:13px;letter-spacing:.13em}header small{display:block;opacity:.75;letter-spacing:0}main{max-width:1100px;margin:auto;background:#fff;padding:46px 56px 72px}h1{font-size:36px;line-height:1.45;letter-spacing:-.025em;margin:0 0 20px;max-width:900px}h2{font-size:25px;line-height:1.5;margin:56px 0 20px;padding-top:20px;border-top:2px solid #d8e5df;scroll-margin-top:20px}h3{font-size:19px;margin-top:30px}p{margin:16px 0}strong{color:#113f3b}code{font: .88em ui-monospace,SFMono-Regular,monospace;background:#edf2ef;padding:2px 5px;border-radius:4px;overflow-wrap:anywhere}pre{background:#132a32;color:#e2eeea;padding:20px;border-radius:10px;overflow:auto;font-size:14px;line-height:1.65}pre code{background:none;color:inherit;padding:0;white-space:pre;overflow-wrap:normal}table{border-collapse:collapse;width:100%;font-size:14px;line-height:1.7;display:block;overflow-x:auto}th,td{border-bottom:1px solid #dbe4e0;text-align:left;padding:12px 14px;min-width:150px}th{background:#edf4ef}tbody tr:nth-child(even){background:#f7f9f7}ul{padding-left:25px}li{margin:10px 0}figure{margin:24px 0}video{display:block;width:100%;aspect-ratio:1.6;background:#10212b;border-radius:12px}figcaption,.fine{font-size:13px;color:#57706b}nav{display:grid;grid-template-columns:1fr 1fr;gap:8px 24px;background:#edf4ef;padding:24px;border-radius:12px;margin:32px 0}nav a{font-size:14px;text-decoration:none}footer{padding:26px;text-align:center;color:#637c74;font-size:13px}.replay{border:1px solid #cddfd5;border-radius:12px;background:#f5f9f5;padding:20px}.controls{display:flex;gap:18px;flex-wrap:wrap;align-items:center}button,select{max-width:100%;font:inherit;padding:8px 12px;border:1px solid #9bb3a5;border-radius:7px;background:white;color:#173f36}button{background:#176954;color:white;cursor:pointer;min-width:84px}input[type=range]{width:100%;accent-color:#176954}.slider-label{display:block;font-size:13px;margin-top:15px}#scene{width:100%;max-height:570px;display:block;background:#e9eeeb;border-radius:8px}#clock{font-variant-numeric:tabular-nums}.legend{display:flex;gap:15px;flex-wrap:wrap;font-size:13px}#state,#event{font-size:14px;overflow-wrap:anywhere}.badge{font-weight:600;color:#12634b;background:#e7f1e9;display:inline-block;padding:4px 12px;border-radius:30px;margin:12px 0} @media(max-width:740px){main{padding:25px 20px 45px}h1{font-size:28px}h2{font-size:22px}nav{grid-template-columns:1fr;padding:18px}th,td{padding:9px;min-width:115px}.replay{padding:12px}.controls{gap:9px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}'''
js='''const D=JSON.parse(document.getElementById('replay-data').textContent);const select=document.getElementById('case'),slider=document.getElementById('time'),button=document.getElementById('play'),svg=document.getElementById('scene');let playing=false,prior=null;const X=x=>(x+4.2)*100,Y=y=>(3.2-y)*100;function stop(){playing=false;button.textContent='Play';prior=null}function draw(){const c=D.cases[+select.value],t=+slider.value;slider.max=c.metrics.sim_duration_s.toFixed(3);let n=0;while(n+1<c.samples.length&&c.samples[n+1].t<=t)n++;const s=c.samples[n];const ev=c.events.filter(e=>e.t<=t);let blocked=false;for(const e of ev){if(e.event==='passage_blocked')blocked=true;if(e.event==='passage_reopened')blocked=false}let shapes=D.obstacles.map(([x,y,rx,ry])=>`<rect x="${X(x-rx)}" y="${Y(y+ry)}" width="${200*rx}" height="${200*ry}" fill="#647a78"/>`).join('');if(blocked)for(const sign of [-1,1])shapes+=`<rect x="${X(-.16)}" y="${Y(2*sign+1)}" width="32" height="200" fill="#d9903e"/>`;shapes+=`<polyline points="${c.samples.slice(0,n+1).map(p=>X(p.xy[0])+','+Y(p.xy[1])).join(' ')}" fill="none" stroke="#13876a" stroke-width="4"/>`;for(const [x,label] of [[-2.5,'H Reception'],[2.5,'D Room A']])shapes+=`<circle cx="${X(x)}" cy="${Y(0)}" r="12" fill="#244c65"/><text x="${X(x)-35}" y="${Y(0)-22}" font-size="18">${label}</text>`;if(s.obstacle)shapes+=`<circle cx="${X(s.obstacle[0])}" cy="${Y(s.obstacle[1])}" r="24" fill="#d4732c" stroke="#fff" stroke-width="2"/>`;shapes+=`<circle cx="${X(s.xy[0])}" cy="${Y(s.xy[1])}" r="10" fill="#08a377" stroke="#fff" stroke-width="3"/><path d="M65 580h100m-100 -5v10m100 -10v10" stroke="#233f3a" stroke-width="3"/><text x="95" y="610" font-size="18">1 m</text>`;svg.innerHTML=shapes;document.getElementById('clock').textContent=t.toFixed(3)+' / '+c.metrics.sim_duration_s.toFixed(3)+' s';document.getElementById('state').textContent=`Observed ${s.t.toFixed(3)} s · ${s.phase} · xy (${s.xy.map(v=>v.toFixed(3)).join(', ')}) m · speed ${s.speed.toFixed(4)} m/s`;document.getElementById('event').textContent='Latest event: '+(ev.length?ev.at(-1).event:'Before first observation (initial position shown)')+' | LLM judgments in this run: '+c.metrics.judgments;}function frame(now){if(!playing)return;if(prior!==null)slider.value=Math.min(+slider.max,+slider.value+(now-prior)/1000);prior=now;draw();if(+slider.value>=+slider.max)stop();else requestAnimationFrame(frame)}select.onchange=()=>{stop();slider.value=0;draw()};slider.oninput=()=>{stop();draw()};button.onclick=()=>{if(playing)stop();else{if(+slider.value>=+slider.max)slider.value=0;playing=true;button.textContent='Pause';requestAnimationFrame(frame)}};draw();'''
body=body.replace('<h2 id="s1">',f'<nav aria-label="Contents">{nav}</nav><h2 id="s1">',1)
page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MissionOS × Go2 — Agent-Supervised Delivery: Technical Report</title><style>{css}</style></head><body><header>MISSIONOS / TECHNICAL REPORT<small>Go2 delivery · Recorded evidence · 2026-09-25</small></header><main>{body}</main><footer>Local edition · Videos and trajectories show recorded simulation observations</footer><script type="application/json" id="replay-data">{dataset}</script><script>{js}</script></body></html>'''
(R/'index-en.html').write_text(page)
print('Rendered',len(md),'Markdown characters;',len(page),'HTML characters')
